services:
  solr:
    image: solr:8.11.4
    environment:
      - SOLR_HEAP=16g
    ports:
      - "127.0.0.1:8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - gettingstarted
    deploy:
      resources:
        limits:
          memory: 16G
volumes:
  data: