version: "3"
services:
  solr:
    image: solr:8.11.4
    ports:
      - "127.0.0.1:8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - gettingstarted
volumes:
  data: